[build]
  publish = "."

[[redirects]]
  from = "/"
  to   = "/student.html"
  status = 200

[[redirects]]
  from = "/student"
  to   = "/student.html"
  status = 200

[[redirects]]
  from = "/admin"
  to   = "/admin.html"
  status = 200
